### ISSUE TITLE
 Failed to migrate

### ISSUE THREAD

**Issue by fmoonc** [thedevsbuddy/adminr#8]
this is the error message when migrating:

INFO  Preparing database.  

  Creating migration table ........................................................... 9ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .............................................. 28ms DONE
  2014_10_12_100000_create_password_resets_table .................................... 11ms DONE
  2019_08_19_000000_create_failed_jobs_table ........................................ 19ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ............................. 19ms DONE
  2021_11_01_000000_create_settings_table ............................................ 6ms DONE
  2021_12_17_160743_create_permission_tables ....................................... 143ms DONE
  2021_12_18_074724_add_resource_column_to_permissions_table ........................ 13ms DONE
  2021_12_18_074724_create_adminr_menus_table ........................................ 9ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'adminr_resources' (SQL: alter table `adminr_menus` add constraint `adminr_menus_resource_foreign` foreign key (`resource`) references `adminr_resources` (`id`) on delete cascade)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
    756▕         // If an exception occurs when attempting to run a query, we'll format the error
    757▕         // message to include the bindings with SQL, which will make this exception a
    758▕         // lot more helpful to the developer instead of just the database's errors.
    759▕         catch (Exception $e) {
  ➜ 760▕             throw new QueryException(
    761▕                 $query, $this->prepareBindings($bindings), $e
    762▕             );
    763▕         }
    764▕     }

      +35 vendor frames 
  36  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by thedevsbuddy** [comment]
Hello, @fmoonc Thank you for pointing out the issue. 
I currently fixed the issue please update `adminr-engine` package to `0.1.8` and then migrate.
it will be fixed. and remember that this project will no longer get any updates as I am creating this project from the ground up again to use a new structure for the project and with new features. With lots of optimization.
